### ISSUE TITLE
Maps are not displayed when viewing the restaurant/directions page

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#36] opened 2013-11-06 12:18 UTC
When viewing a page of a restaurant, there is no map displayed. Same happens if you go to the map page (by clicking on invisible map at the restaurant page).

**Comment by tdeekens** [comment] 2013-11-06 13:12
Cannot reproduce on OS X Mavericks with one of the following
- Chrome 30
- Chrome Canary 33
- Safari 7
- Firefox 24

**Comment by tdeekens** [comment] 2013-11-06 13:24
Closed as being @anna-averianova Firefox being a jerk.

**Closed as completed by tdeekens** 2013-11-06 13:24 UTC
Labels: bug
